# Generated by Django 5.0.2 on 2024-11-29 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaratteristicheFisiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scelta_Caratteristiche', models.CharField(choices=[('SOTTOP', 'Sottopeso'), ('NORMOP', 'Normopeso'), ('SOVRAP', 'Sovrappeso')], default='', max_length=50)),
            ],
            options={
                'verbose_name': 'CaratteristicheFisiche',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('bodypart', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('reatingdesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('altezza', models.DecimalField(decimal_places=2, help_text="Inserisci l'altezza in cm", max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Inserisci il peso in kg', max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='ObiettivoFitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obiettivo', models.CharField(choices=[('D', 'Dimagrimento'), ('M', 'Massa muscolare'), ('F', 'Mantenere la forma fisica'), ('A', 'Altro')], max_length=1)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.member')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.member')),
                ('workouts', models.ManyToManyField(to='fitness.workout')),
            ],
        ),
    ]
