# Generated by Django 5.0.2 on 2024-03-07 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_member_joined_date_remove_member_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaratteristicheFisiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scelta_Caratteristiche', models.CharField(choices=[('SOTTOP', 'Sottopeso'), ('NORMOP', 'Normopeso'), ('SOVRAP', 'Sovrappeso')], default='', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Utenti'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='cognome',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='data_iscrizione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='nome',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ObiettivoFitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obiettivo', models.CharField(choices=[('P', 'Perdere peso'), ('A', 'Aumentare massa muscolare'), ('F', 'Mantenere la forma fisica'), ('A', 'Altri')], max_length=1)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
