# Generated by Django 5.0.2 on 2024-11-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_statistiche_alter_obiettivofitness_obiettivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistiche',
        ),
    ]
