# Generated by Django 5.0.2 on 2024-11-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_delete_statistiche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caratteristichefisiche',
            options={'verbose_name': 'CaratteristicheFisiche'},
        ),
        migrations.AlterField(
            model_name='obiettivofitness',
            name='obiettivo',
            field=models.CharField(choices=[('D', 'Dimagrimento'), ('M', 'Massa muscolare'), ('F', 'Mantenere la forma fisica'), ('A', 'Altro')], max_length=1),
        ),
    ]
