# Generated by Django 5.0.2 on 2024-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_caratteristichefisiche_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='altezza',
            field=models.DecimalField(decimal_places=2, default=170, help_text="Inserisci l'altezza in cm", max_digits=5),
        ),
        migrations.AddField(
            model_name='member',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Inserisci il peso in kg', max_digits=5),
        ),
    ]
